#ifndef SC_DEFINES_H_
#define SC_DEFINES_H_

#include <scir.h>
#include <common.h>

// Scir Block Size Controls
#define SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ (SC_SCIR_BLOCK_MAX_OPS_INT_ * sizeof(ScirOp))

#define SC_SCIR_BLOCK_OP_LIFETIME_SIZE_INT (SC_SCIR_BLOCK_MAX_OPS_INT_ * sizeof(u16))

#define SC_SCIR_BLOCK_USE_ARRAY_SIZE_INT_ (SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ * 2 * sizeof(u16))

#define SC_SCIR_BLOCK_CONST_ARRAY_SIZE_INT_ (SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ * 2 * sizeof(u32))

#define SC_SCIR_BLOCK_SIZE_INT_ (SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ + SC_SCIR_BLOCK_OP_LIFETIME_SIZE_INT + SC_SCIR_BLOCK_USE_ARRAY_SIZE_INT_ + SC_SCIR_BLOCK_CONST_ARRAY_SIZE_INT_)

// Dreamcast specific values
#define SC_DC_MAIN_MEMORY_SIZE_INT_ 16777216 // 16 MiB

#define SC_DC_VIDEO_MEMORY_SIZE_INT_ 8388608 // 8 MiB

#define SC_DC_AICA_MEMORY_SIZE_INT_ 2097152 // 2 MiB

#define SC_DC_MEMORY_SIZE_INT_ (SC_DC_MAIN_MEMORY_SIZE_INT_ + SC_DC_VIDEO_MEMORY_SIZE_INT_ + SC_DC_AICA_MEMORY_SIZE_INT_)

#endif