#ifndef SC_DEFINES_H_
#define SC_DEFINES_H_

#include <scir.h>
#include <common.h>

// Scir Block Size Controls
#define SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ (SC_SCIR_BLOCK_MAX_OPS_INT_ * sizeof(ScirOp))

#define SC_SCIR_BLOCK_OP_LIFETIME_SIZE_INT (SC_SCIR_BLOCK_MAX_OPS_INT_ * sizeof(u16))

#define SC_SCIR_BLOCK_USE_ARRAY_SIZE_INT_ (SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ * 2 * sizeof(u16))

#define SC_SCIR_BLOCK_CONST_ARRAY_SIZE_INT_ (SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ * 2 * sizeof(u32))

#define SC_SCIR_BLOCK_SIZE_INT_ (SC_SCIR_BLOCK_OP_ARRAY_SIZE_INT_ + SC_SCIR_BLOCK_OP_LIFETIME_SIZE_INT + SC_SCIR_BLOCK_USE_ARRAY_SIZE_INT_ + SC_SCIR_BLOCK_CONST_ARRAY_SIZE_INT_)

#endif